name: build-push-deploy

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: philippzagar/tum4health_cms:latest
          cache-from: type=registry,ref=philippzagar/tum4health_cms:buildcache
          cache-to: type=registry,ref=philippzagar/tum4health_cms:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: "ubuntu@130.61.218.40"
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          args: up -d
          deploy_path: /home/ubuntu/tum4health-cms
          stack_file_name: docker-compose.deploy.yml
          copy_stack_file: true
          keep_files: 5
          docker_prune: "true"
          pull_images_first: "true"
    needs: build-push
